export class Application {
  constructor(public id: number,
              public submitted: string,
              public tripDate: string,
              public first: string,
              public middle: string,
              public last: string,
              public addressLine1: string,
              public addressLine2: string,
              public city: string,
              public state: string,
              public zip: string,
              public homePhone: string,
              public cellPhone: string,
              public email: string,
              public month: string,
              public day: string,
              public year: string,
              public nationality: string,
              public birthPlace: string,
              public maidenName: string,
              public maritalStatus: string,
              public gender: string,
              public passportNumber: string,
              public passportIssueDateMonth: string,
              public passportIssueDateDay: string,
              public passportIssueDateYear: string,
              public passportExpirationDateMonth: string,
              public passportExpirationDateDay: string,
              public passportExpirationDateYear: string,
              public question1: string,
              public question2: string,
              public question3: string,
              public question4: string,
              public question5: string,
              public question6: string,
              public person1Name: string,
              public person1Relationship: string,
              public person1Phone: string,
              public person1Email: string,
              public person2Name: string,
              public person2Relationship: string,
              public person2Phone: string,
              public person2Email: string) {
  }
}
